export * from './createFrequency.service'
export * from './createFrequencyStudent.service'
export * from './deleteFrequency.service'
export * from './listFrequency.service'
export * from './listFrequencyStudent.service'
export * from './retrieveFrequency.service'
export * from './updateFrequency.service'
export * from './updateFrequencyStudent.service'
